const industryOptions = [
  "Accounting / Auditing",
  "Advertising & Marketing",
  "Agriculture / Forestry / Fishing",
  "Analytics / KPO / Research",
  "Animation & VFX",
  "Architecture / Interior Design",
  "Auto Components",
  "Automobile",
  "Aviation",
  "Banking",
  "Beauty & Personal Care",
  "Beverage",
  "Biotechnology",
  "BPM / BPO",
  "Building Material",
  "Chemicals",
  "Consumer Electronics & Appliances",
  "Content Development / Language",
  "Courier / Logistics",
  "Defence & Aerospace",
  "Design",
  "E-Learning / EdTech",
  "Education / Training",
  "Electrical Equipment",
  "Engineering & Construction",
  "Events / Live Entertainment",
  "Facility Management Services",
  "Fertilizers / Pesticides / Agro chemicals",
  "Film / Music / Entertainment",
  "FinTech / Payments",
  "Fitness & Wellness",
  "FMCG",
  "Food Processing",
  "Furniture & Furnishing",
  "Gaming",
  "Gems & Jewellery",
  "Government / Public Administration",
  "Hardware & Networking",
  "Hotels & Restaurants",
  "Industrial Automation",
  "Industrial Equipment / Machinery",
  "Insurance",
  "Internet",
  "Investment Banking / Venture Capital / Private Equity",
  "Iron & Steel",
  "IT Services & Consulting",
  "Law Enforcement / Security Services",
  "Leather",
  "Legal",
  "Management Consulting",
  "Medical Devices & Equipment",
  "Medical Services / Hospital",
  "Metals & Mining",
  "Miscellaneous",
  "NBFC",
  "Oil & Gas",
  "Packaging & Containers",
  "Petrochemical / Plastics / Rubber",
  "Pharmaceutical & Life Sciences",
  "Ports & Shipping",
  "Power",
  "Printing & Publishing",
  "Real Estate",
  "Recruitment / Staffing",
  "Retail",
  "Semiconductors",
  "Software Product",
  "Telecom",
  "Textile & Apparel",
  "Travel & Tourism",
  "Waste Management",
];

export default industryOptions;