const roleCategories = [
  "Retail & B2C Sales",
  "BD / Pre Sales",
  "Voice / Blended",
  "Enterprise & B2B Sales",
  "Sales Support & Operations",
  "Customer Success & Service",
  "Software Development",
  "Finance & Accounting - Other",
  "Other Hospital Staff",
  "Healthcare & Life Sciences",
  "Operations",
  "Operations, Maintenance & Support",
  "Business Process Quality",
  "Content, Editorial & Journalism",
  "Legal & Regulatory - Other",
  "BFSI, Investments & Trading",
  "Non Voice",
  "Data Science & Machine Learning",
  "Engineering",
  "Back Office",
  "Quality Assurance and Testing",
  "Accounting & Taxation",
  "Employee Relations",
  "Human Resources - Other",
  "Digital Marketing",
  "Marketing",
  "Production & Manufacturing",
  "Quality Assurance - Other",
  "Fashion & Accessories",
  "Other Design",
  "Administration",
  "Management Consulting",
  "Other Consulting",
  "Journalism",
  "Pharmaceutical & Biotechnology",
  "Research & Development",
  "Security Services - Other",
  "Administration & Staff",
  "Other"
];

export default roleCategories;